name: CI

on:
  push:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test-and-deploy:
    name: Test and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          verion: 7.12.2

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test run
